# Generated by Django 5.1.3 on 2025-05-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='detail',
            new_name='detail_about',
        ),
    ]
