# Generated by Django 5.1.3 on 2025-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_detail_question_detail_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='detail_about',
            new_name='detail',
        ),
    ]
