# Generated by Django 5.1.3 on 2024-11-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_nested',
            field=models.BooleanField(default=False),
        ),
    ]
