# Generated by Django 5.1.3 on 2025-03-22 12:21

import src.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_course_is_nested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=src.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=src.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=src.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='img',
            field=src.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
